apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: blue
  name: blue
spec:
  replicas: 6
  selector:
    matchLabels:
      run: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: blue
    spec:
      containers:
      - image: nginx
        name: blue
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In
                  values:
                    - blue
status: {}